services:
  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
      target: production
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
