services:
  backend-green:
    extends:
      file: docker-compose.yml
      service: backend
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    networks:
      - app-network

  frontend-green:
    extends:
      file: docker-compose.yml
      service: frontend
    environment:
      - BACKEND_URL=http://backend-green:3000
    networks:
      - app-network
    extra_hosts:
      - "db-host:${DATABASE_HOST}"
networks:
  app-network:
    driver: bridge 
