services:
  backend-green:
    extends:
      file: Docker-compose.yml
      service: backend
      env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_NAME: ${{ secrets.MYSQL_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
      run: |
          echo "Setting up environment variables"
          echo "MYSQL_HOST=${MYSQL_HOST}" >> .env
          echo "MYSQL_PORT=${MYSQL_PORT}" >> .env
          echo "MYSQL_USER=${MYSQL_USER}" >> .env
          echo "MYSQL_PASSWORD=${MYSQL_PASSWORD}" >> .env
          echo "MYSQL_NAME=${MYSQL_NAME}" >> .env
          echo "DB_HOST=${DB_HOST}" >> .env

    networks:
      - app-network

  frontend-green:
    extends:
      file: Docker-compose.yml
      service: frontend
    environment:
      - BACKEND_URL=http://backend-green:3000
    networks:
      - app-network
    extra_hosts:
      - "db-host:${DB_HOST}"
networks:
  app-network:
    driver: bridge 
