services:
  backend-green:
    extends:
      file: Docker-compose.yml
      service: backend
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_NAME=${MYSQL_NAME}
      - DB_HOST=${DB_HOST}
    networks:
      - app-network

  frontend-green:
    extends:
      file: Docker-compose.yml
      service: frontend
    environment:
      - BACKEND_URL=http://backend-green:3000
    networks:
      - app-network
    extra_hosts:
      - "db-host:${DB_HOST}"

networks:
  app-network:
    driver: bridge