services:
  backend-blue:
    extends:
      file: Docker-compose.yml
      service: backend
    ports:
      - "3000:3000"
      - "9001:9001"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - DB_HOST=${DB_HOST}
    networks:
      - app-network

  frontend-blue:
    ports:
      - "80:80"
    extends:
      file: Docker-compose.yml
      service: frontend
    environment:
      - BACKEND_URL=http://backend-green:3000
    networks:
      - app-network
    extra_hosts:
      - "db-host:${DB_HOST}"

networks:
  app-network:
    driver: bridge