services:
  backend-blue:
    extends:
      file: docker-compose.yml
      service: backend
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_NAME=${MYSQL_NAME}
    networks:
      - app-network
    extra_hosts:
      - "db-host:${DB_HOST}"


  frontend-blue:
    extends:
      file: docker-compose.yml
      service: frontend
    environment:
      - BACKEND_URL=http://backend-blue:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
